name: podcasts_pro
description: "A project to listen to podcasts through RSS subscription links."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.19

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dart_rss: ^3.0.3
  dio: ^5.5.0+1
  xml: ^6.5.0
  http: ^1.2.2
  html: ^0.15.4
  cached_network_image: ^3.4.0
  shared_preferences: ^2.3.1
  just_audio: ^0.9.39
  intl: ^0.19.0
  flutter_slidable: ^3.1.1
  audio_service: ^0.18.15
  audio_session: ^0.1.21
  rxdart: ^0.28.0
  flutter_html: ^3.0.0-beta.2  
  cupertino_icons: ^1.0.6
  flutter_splash_screen: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  assets:
    - assets/images/

  uses-material-design: true
