name: Flutter Release

on:
  push:
    tags:
      - 'v*' # 这将匹配所有以v开头的tag，例如v1.0.0, v2.1.3等

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x' # 使用最新的稳定版本
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Run tests
      run: flutter test
    
    - name: Build APK
      run: flutter build apk --release
    
    - name: Build App Bundle
      run: flutter build appbundle --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
    
    - name: Upload App Bundle
      uses: actions/upload-artifact@v2
      with:
        name: release-bundle
        path: build/app/outputs/bundle/release/app-release.aab

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Download APK
      uses: actions/download-artifact@v2
      with:
        name: release-apk
    
    - name: Download App Bundle
      uses: actions/download-artifact@v2
      with:
        name: release-bundle
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: Upload APK Asset
      uses: actions/upload-release-asset@v1
      env:
        RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app-release.apk
        asset_name: app-release.apk
        asset_content_type: application/vnd.android.package-archive
    
    - name: Upload App Bundle Asset
      uses: actions/upload-release-asset@v1
      env:
        RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app-release.aab
        asset_name: app-release.aab
        asset_content_type: application/octet-stream
